#!/usr/bin/env bash

# This file includes a command that transfers a file from the client to a server.

if (($# < 3)); then
	echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY";
else
	scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~/;
fi
