#!/usr/bin/env bash

# This script install nginx on our server.

sudo apt-get update
sudo apt-get -y install nginx
ufw allow 'Nginx HTTP'
sudo su
echo "Hello World!" > /var/www/html/index.html
service nginx start
