#!/usr/bin/env bash
# Install NGINX on our remote server
sudo apt-get -y update
sudo apt-get -y install nginx

# create the html file
echo "Hello World!" | sudo tee /var/www/html/index.html

# start the server
sudo systemctl start nginx
