#!/usr/bin/env bash
# Install NGINX on our remote server
sudo apt update
sudo apt -y install nginx
sudo ufw allow 'Nginx HTTP'

# create the html file
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo service nginx start
