#!/usr/bin/env bash
# Install nginx web server
redirect="\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n"
sudo apt-get -y update
sudo apt-get -y install nginx
sudo sed -i "51i $redirect" /etc/nginx/sites-available/default #add at line 51
sudo service nginx start
