#!/usr/bin/env bash
#Script that installs HAPROXY server, confiugres it with a custom header.

# Install Nginx
sudo apt update -y

sudo apt install -y haproxy

# Configure HAProxy to add custom HTTP header
echo 'frontend http_front
  bind *:80
  stats uri /haproxy?stats
  default_backend http_back

backend http_back
  balance roundrobin
  server 33210-web-01 52.201.153.166 check
  server 33210-web-02 54.160.108.108 check' | sudo tee /etc/haproxy/haproxy.cfg

# Check the HAProxy configuration
sudo haproxy -c -f /etc/haproxy/haproxy.cfg

# Start HAProxy service
sudo service haproxy start
