#!/usr/bin/env bash
# Redirect.

# Open UFW configuration file for editing
sudo nano /etc/ufw/before.rules <<EOF
# Redirect traffic from port 8080 to port 80
*nat
:PREROUTING ACCEPT [0:0]
-A PREROUTING -p tcp --dport 8080 -j REDIRECT --to-port 80
COMMIT
EOF

# Reload UFW rules to apply changes
sudo ufw reload
