#!/usr/bin/env bash

# Create the file
echo "Hello Holberton" > index.txt

# Pull the apache image from docker hun
docker pull httpd:latest

# Run the apache container
docker run -d -p 8080:80 httpd:latest

# Acess our created file
docker run -d -p 8080:80 -v "$(pwd)/index.txt:/usr/local/apache2/htdocs/index.html" httpd:latest
